### ISSUE TITLE
Python3 documentation - Tutorial

### ISSUE THREAD

**Issue by Schamnad** [cclib/cclib.github.io#13]
To find more discrepancies in the documentation, I decided to begin everything from scratch. 
In the tutorial section, the code provided to test both numpy and cclib assumes that the installation will be completed using python 3, but this might be false as in majority of the systems including mine (Ubuntu 15.10) the default python version is 2.7.x i.e. the[ "python" command](https://www.python.org/dev/peps/pep-0394/)

Given the case, I get these errors when I follow the tutorial as is.

> sanjeed@sanjeed-PC:/media/sanjeed/Mine/GitHub/repos$ python3
> Python 3.4.3+ (default, Oct 14 2015, 16:03:50) 
> [GCC 5.2.1 20151010] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import numpy
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: No module named 'numpy'
> >>> import cclib
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: No module named 'cclib'

but when I use just python to start the python interpretor

> sanjeed@sanjeed-PC:/media/sanjeed/Mine/GitHub/repos$ python
> Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
> [GCC 5.2.1 20151010] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import numpy
> >>> numpy.__version__
> '1.8.2'
> >>> import cclib
> >>> cclib.__version__
> '1.3.1

The same ImportError is obtained while starting cclib using python3 in accordance to the tutorial. 

Have I missed something in the installation or is my premise of assuming that cclib and numpy have been installed for python 2.7.x right?

**Comment by berquist** [comment]
> In the tutorial section, the code provided to test both numpy and cclib assumes that the installation will be installed using python 3

The documentation here is vague, yes. You should install `python3-numpy` on Debian/Ubuntu, however the official `cclib` is Python 2 only for all old Ubuntu versions except Xenial, where you can additionally install the `python3-cclib` package: http://packages.ubuntu.com/search?keywords=cclib&searchon=names&suite=all&section=all

For Python 2, `python-numpy` and `cclib` are sufficient; I think `python-cclib` gets installed automatically as a `cclib` dependency.

**Comment by Schamnad** [comment]
Since the official `cclib` is based on Python 2 and the tutorial page tells the user to install `python-numpy` instead of `python3-numpy`, wouldn't it be better if the tutorial is based on them? I am trying to look at it from the perspective of a new user.

**Comment by langner** [comment]
We support both Python 2 and 3 for cclib, and test multiple versions (https://travis-ci.org/cclib/cclib). That is as official as it gets. Now what is in the Debian/Ubuntu repositories is another matter... when I started making the cclib package for Debian I planned to do the Py3 version but got sidetracked. I haven't touched it in over a year, and the good people of debichem have been maintaining it. It'd be useful to get the py3 version in there, too.

I think we should try to be version agnostic, and simply enumerate the differences in installation/configs where needed.

**Comment by Schamnad** [comment]
Sure, makes sense. I shall close this issue now as this is not a bug per se.
