### ISSUE TITLE
Updates for v1.5

### ISSUE THREAD

**Issue by langner** [cclib/cclib.github.io#20]
Some things to update around the release:
- The stuff mentioned in cclib/cclib#257
- Add the MOPAC parser
- Describe any new attributes

**Comment by mbanck** [comment]
1.5 has long since happened, and apart from the above, the webpage still mentions 1.4 as latest version all over the place.

**Comment by langner** [comment]
Thanks, Michael, for pushing this along. Created cclib/cclib.github.io#22 and will merge it tomorrow if no one from cclib has comments.
