### ISSUE TITLE
Fix conf to work with Sphinx 1.5

### ISSUE THREAD

**Issue by berquist** [cclib/cclib.github.io#26]
There have been quite a few changes to Sphinx (see the [revlog](http://www.sphinx-doc.org/en/stable/changes.html)), most notably https://github.com/sphinx-doc/sphinx/pull/2454 which messes up the way some file extensions work; right now, it produces a bunch of `_sources/*.rst.txt` files.

**Comment by langner** [comment]
We're currently using v1.7.8.
