### ISSUE TITLE
NPA charges from Gaussian 09 output wrongly parsed

### ISSUE THREAD

**Issue by stefabat** [cclib/cclib.github.io#28]
Hey there,

I would like to notify a bug regarding the parsing of NPA charges from a gaussian09 log file (d01 version),  computed using NBO6, but I believe is the same also with the gaussian builtin NBO3 program.

The bug appears when parsing natural charges for molecules having more than 99 atoms.
When this is the case, there is no more space between the symbol of the atom and the atom number in the output of the natural population analysis, e.g.

...
H 98  ...
H 99  ...
H100 ...
...

And basically, the charges starting at 100 are just nuts.
It suffices however to modify the log file of gaussian and add a space between the atom symbol and the atom number to get the correct values of the charges parsed.

Cheers
stefabat

**Comment by langner** [comment]
Hi Stefano. Thanks for the report - could you create an issue in our main repo for the code (https://github.com/cclib/cclib/issues), please? We would be happy to fix this if you could donate an example logfile that has this problem.

**Comment by langner** [comment]
Copied to cclib/cclib#406

**Comment by langner** [comment]
Please note I'm going to close cclib/cclib#406 due to inactivity soone.
