### ISSUE TITLE
Cannot use ccwrite method on Mac OS. 

### ISSUE THREAD

**Issue by szl0072** [cclib/cclib.github.io#34]
`Traceback (most recent call last):
  File "/Users/username/anaconda3/bin/ccwrite", line 4, in <module>
    __import__('pkg_resources').run_script('cclib==1.5.2', 'ccwrite')
  File "/Users/username/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/username/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1516, in run_script
    code = compile(source, script_filename, 'exec')
  File "/Users/username/anaconda3/lib/python3.6/site-packages/cclib-1.5.2-py3.6.egg/EGG-INFO/scripts/ccwrite", line 45
    type=int,
       ^
SyntaxError: invalid syntax`

The above information was generated when I was trying to use the ccwrite method on my Mac OS system. I know in the document, it states about usage on various Linux systems. If this problem is mainly happening on Mac OS, I will try to use the library on Linux machines. However, I feel like it is worthy to mention here. If it is my misunderstanding of using the library, I am sorry for the inconvenience beforehand.

**Comment by langner** [comment]
@szl0072 Is there a reason you closed this? What was the setting you got this error in?

**Comment by langner** [comment]
Ah, it's in the wrong repo :)

**Comment by langner** [comment]
New issue is in https://github.com/cclib/cclib/issues/468

**Comment by szl0072** [comment]
@langner. Yes, and sorry I did not put them in the right repo. So I closed it up. For the record, I was on Mac OS, using Python3. And I think one another developer already caught this issue.
