### ISSUE TITLE
Add some usage examples to tutorial

### ISSUE THREAD

**Issue by langner** [cclib/cclib.github.io#6]
What I have in mind:
- example for simple parsing using `ccget`
- example for simple parsing within Python
- example for using a method
- example for using a bridge
- ...

**Comment by Schamnad** [comment]
I have started working on resolving this issue. I have presently made an example.rst file containing examples for simple parsing using ccget. I will be working on the other aspects in the upcoming week.

Presently I have submitted a [pull request](https://github.com/cclib/cclib.github.io/pull/14) for the first feature.

**Comment by langner** [comment]
Relevant: #30

**Comment by langner** [comment]
Most of this was done, we'll add more as needed.
